### ISSUE TITLE
how to enable local sentence reordering?

### ISSUE THREAD

**Issue by fish-inu** [thompsonb/vecalign#13]
Greetings! I read through the paper and came cross this line: 

> Following prior work, we assume non-crossing alignments but allow local sentence reordering within an alignment.

But I find nowhere local sentence reordering is explained. Can give me some insight into it?

**Comment by thompsonb** [comment]
Suppose you have an English document with sentences a, b, c, and d, and a French document with sentences A, C, B, D, where A is a translation of a, B is a translation of b, etc.

They algorithm won't find (a,A), (b,B), (c,C), (d,D) because (b,B) and (c,C) alignments are crossing. Instead it will find (a,A), (b+c, C+B), (d,D). 

(b+c, C+B) has local (i.e. within an alignment) re-ordering.

**Comment by fish-inu** [comment]
Got it! Thanks!
