### ISSUE TITLE
RuntimeWarning: overflow encountered in square

### ISSUE THREAD

**Issue by pmetel** [thompsonb/vecalign#2]
hi, I often see the warning:

dp_utils.py:112: RuntimeWarning: overflow encountered in square
  norm = np.sqrt(np.square(vecs0[ii, jj, :]).sum())

I can provide sample data if you need. Thx

**Comment by thompsonb** [comment]
I don't think I've seen this. If you can provide a small example (text files and embedding files), I'll look into it.

**Comment by pmetel** [comment]
[sample1.zip](https://github.com/thompsonb/vecalign/files/4195159/sample1.zip)

**Comment by thompsonb** [comment]
Are you passing the *.npy files to vecalign.py? It is expecting a binary file which matches the format output from https://github.com/facebookresearch/LASER/blob/master/tasks/embed/embed.sh.

If so, the problem is that your data is being interpreted incorrectly, resulting in some very large values:

import numpy as np
from dp_utils import read_in_embeddings
sents, vecs = read_in_embeddings('sample1/sample.en.overlap', 'sample1/sample.en.overlap.npy')
np.set_printoptions(precision=3, linewidth=120)
print(vecs[0][:10])
[2.237e+08 1.239e-40 3.483e-15 4.490e+21 1.577e-19 2.144e-07 2.223e-15 7.683e+31 1.718e+19 6.743e+22]

If I embed your overlap files using LASER, it seems to work fine:
embed.sh sample1/sample.en.overlap en sample1/sample.en.overlap.emb
embed.sh sample1/sample.pl.overlap pl sample1/sample.pl.overlap.emb

./vecalign.py --alignment_max_size 3 --src sample1/sample.en --tgt sample1/sample.pl \
   --src_embed sample1/sample.en.overlap sample1/sample.en.overlap.emb \
   --tgt_embed sample1/sample.pl.overlap sample1/sample.pl.overlap.emb
[0]:[0]:0.439750
[1]:[1]:0.894222
[2]:[2]:0.585108
[3]:[3]:0.505411
[4]:[4]:0.468621
[5]:[5]:0.596084
[6]:[6]:0.376622
[7]:[7]:0.549877
[8]:[8]:0.538891
[9]:[9]:0.564209
[10, 11]:[10]:0.541934
[12]:[]:0.000000

**Comment by pmetel** [comment]
That's it. Thanks!
I was saving embeddings with numpy.save method where .tofile makes different format.
What confused me was that the results were looking quite good with wrong embeddings.
Btw. I'm using https://github.com/yannvgn/laserembeddings and now it gives the same results as original LASER.

I've been also checking https://github.com/UKPLab/sentence-transformers/blob/master/docs/pretrained-models/multilingual-models.md
and the results looks promising, for bleualign_data/test* I got:


|             |  Strict |    Lax  |
| Precision   |   0.880 |   0.992 |
| Recall      |   0.883 |   0.988 |
| F1          |   0.882 |   0.990 |

 

Thank you for great work!

**Comment by thompsonb** [comment]
No problem. 

Those numbers look good - thanks for sharing. I'll be curious to see how distiluse-base-multilingual-cased was trained once they post more details.
